### ISSUE TITLE
where the bloody hell is the download??

### ISSUE THREAD

**Issue by ItssHarley** [Uuketi/Checkpoint-Monk#3]
where is it mate

**Comment by Xemply** [comment]
https://github.com/Uuketi/Checkpoint-Monk/releases/download/1.0.0/CheckpointMonk_v1.0.0.qmod here

**Comment by ZaveDrD** [comment]
where can i see the code

**Comment by Xemply** [comment]
There is no source code

**Comment by Uuketi** [comment]
You guys need to learn how to use github i dont understand how you haven't been downloading the source code of other peoples mods this whole time, its in the releases section.

**Comment by Xemply** [comment]
Bro it’s bcz I wanna see the code not download the mod lol Ik how to use github lol
